export const CHAT_SEND_MESSAGE_REQUEST = "CHAT_SEND_MESSAGE_REQUEST";
export const CHAT_SEND_MESSAGE_SUCCESS = "CHAT_SEND_MESSAGE_SUCCESS";
export const CHAT_SEND_MESSAGE_FAIL = "CHAT_SEND_MESSAGE_FAIL";
export const CHAT_RESET = "CHAT_RESET";