export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const EXERCISE_DETAILS_REQUEST = "EXERCISE_DETAILS_REQUEST";
export const EXERCISE_DETAILS_SUCCESS = "EXERCISE_DETAILS_SUCCESS";
export const EXERCISE_DETAILS_FAIL = "EXERCISE_DETAILS_FAIL";