export const EXERCISE_LIST_REQUEST = "EXERCISE_LIST_REQUEST";
export const EXERCISE_LIST_SUCCESS = "EXERCISE_LIST_SUCCESS";
export const EXERCISE_LIST_FAIL = "EXERCISE_LIST_FAIL";

export const EXERCISE_DETAILS_REQUEST = "EXERCISE_DETAILS_REQUEST";
export const EXERCISE_DETAILS_SUCCESS = "EXERCISE_DETAILS_SUCCESS";
export const EXERCISE_DETAILS_FAIL = "EXERCISE_DETAILS_FAIL";
export const EXERCISE_DETAILS_RESET = "EXERCISE_DETAILS_RESET";

export const EXERCISE_SAVE_REQUEST = "EXERCISE_SAVE_REQUEST";
export const EXERCISE_SAVE_SUCCESS = "EXERCISE_SAVE_SUCCESS";
export const EXERCISE_SAVE_FAIL = "EXERCISE_SAVE_FAIL";
export const EXERCISE_SAVE_RESET = "EXERCISE_SAVE_RESET";

export const EXERCISE_DELETE_REQUEST = "EXERCISE_DELETE_REQUEST";
export const EXERCISE_DELETE_SUCCESS = "EXERCISE_DELETE_SUCCESS";
export const EXERCISE_DELETE_FAIL = "EXERCISE_DELETE_FAIL";
export const EXERCISE_DELETE_RESET = "EXERCISE_DELETE_RESET";