export const PROGRAM_GENERATE_REQUEST = "PROGRAM_GENERATE_REQUEST";
export const PROGRAM_GENERATE_SUCCESS = "PROGRAM_GENERATE_SUCCESS";
export const PROGRAM_GENERATE_FAIL = "PROGRAM_GENERATE_FAIL";
export const PROGRAM_RESET = "PROGRAM_RESET";
