export const PROGRESS_ANALYTICS_REQUEST = "PROGRESS_ANALYTICS_REQUEST"
export const PROGRESS_ANALYTICS_SUCCESS = "PROGRESS_ANALYTICS_SUCCESS"
export const PROGRESS_ANALYTICS_FAIL = "PROGRESS_ANALYTICS_FAIL"