export const WORKOUT_LOG_LIST_REQUEST = "WORKOUT_LOG_LIST_REQUEST";
export const WORKOUT_LOG_LIST_SUCCESS = "WORKOUT_LOG_LIST_SUCCESS";
export const WORKOUT_LOG_LIST_FAIL = "WORKOUT_LOG_LIST_FAIL";

export const WORKOUT_LOG_CREATE_REQUEST = "WORKOUT_LOG_CREATE_REQUEST";
export const WORKOUT_LOG_CREATE_SUCCESS = "WORKOUT_LOG_CREATE_SUCCESS";
export const WORKOUT_LOG_CREATE_FAIL = "WORKOUT_LOG_CREATE_FAIL";

export const WORKOUT_LOG_DELETE_REQUEST = "WORKOUT_LOG_DELETE_REQUEST";
export const WORKOUT_LOG_DELETE_SUCCESS = "WORKOUT_LOG_DELETE_SUCCESS";
export const WORKOUT_LOG_DELETE_FAIL = "WORKOUT_LOG_DELETE_FAIL";

export const DASHBOARD_STATS_REQUEST = "DASHBOARD_STATS_REQUEST";
export const DASHBOARD_STATS_SUCCESS = "DASHBOARD_STATS_SUCCESS";
export const DASHBOARD_STATS_FAIL = "DASHBOARD_STATS_FAIL";
